#!/bin/bash

# docker hub's variable 'SOURCE_BRANCH' is used as 
# * monero branch/tag to clone
# * docker image tag to push

docker pull $DOCKER_REPO:dependencies1 || true

docker build \
  --pull \
  --target dependencies1 \
  --cache-from $DOCKER_REPO:dependencies1 \
  -f ./Dockerfile \
  -t $DOCKER_REPO:dependencies1 .

docker push $DOCKER_REPO:dependencies1

docker pull $DOCKER_REPO:builder_monero || true

docker build \
  --pull \
  --target builder_monero \
  --cache-from $DOCKER_REPO:dependencies1 \
  --cache-from $DOCKER_REPO:builder_monero \
  --build-arg BRANCH=$SOURCE_BRANCH \
  -f ./Dockerfile \
  -t $DOCKER_REPO:builder_monero .

docker push $DOCKER_REPO:builder_monero

docker pull $IMAGE_NAME:builder || true

docker build \
  --pull \
  --target builder \
  --cache-from $DOCKER_REPO:dependencies1 \
  --cache-from $DOCKER_REPO:builder_monero \
  --cache-from $DOCKER_REPO:builder \
  --build-arg BRANCH=$SOURCE_BRANCH \
  -f ./Dockerfile \
  -t $IMAGE_NAME:builder .

docker push $DOCKER_REPO:builder

docker pull $IMAGE_NAME || true

docker build \
  --pull \
  --cache-from $DOCKER_REPO:dependencies1 \
  --cache-from $DOCKER_REPO:builder_monero \
  --cache-from $DOCKER_REPO:builder \
  --cache-from $IMAGE_NAME \
  --build-arg BRANCH=$SOURCE_BRANCH \
  -f ./Dockerfile \
  -t $IMAGE_NAME .
