#!/bin/bash

MOST_RECENT_TAG=$(curl -s https://api.github.com/repos/monero-project/monero/tags | grep -i name | awk 'NR==1{print $2}' | tr -d "\",")
if [ "$MOST_RECENT_TAG" = "$DOCKER_TAG" ]; then
  docker tag $IMAGE_NAME $DOCKER_REPO:most_recent_tag
  docker push $DOCKER_REPO:most_recent_tag
elif [ "$SOURCE_BRANCH" = "most_recent_tag" ]; then
  docker tag $IMAGE_NAME $DOCKER_REPO:$MOST_RECENT_TAG
  docker push $DOCKER_REPO:$MOST_RECENT_TAG
elif [ "$SOURCE_BRANCH" = "master" ]; then
  MASTER_COMMIT_SHA=$(curl -s https://api.github.com/repos/monero-project/monero/branches/master  | grep -i sha | awk 'NR==1{print $2}' | tr -d "\",")
  docker tag $IMAGE_NAME $DOCKER_REPO:"$MASTER_COMMIT_SHA"
  docker push $DOCKER_REPO:"$MASTER_COMMIT_SHA"
fi
#   curl -X POST \
#        -F token=$EXPLORER_TOKEN \
#        -F ref=mainnet \
#        $EXPLORER_URL
#   curl -X POST \
#        -F token=$EXPLORER_TOKEN \
#        -F ref=stagenet \
#        $EXPLORER_URL
# fi
# 
# if [ "$TESTNET_BRANCH" = "$SOURCE_BRANCH" ]; then
#   curl -X POST \
#        -F token=$EXPLORER_TOKEN \
#        -F ref=testnet \
#        $EXPLORER_URL
